### ISSUE TITLE
plugin installing and run for iOS error

### ISSUE THREAD

**Issue by DnV1eX** [onsip/onsip-cordova#9]
cordova plugin add https://github.com/onsip/onsip-cordova.git
Fetching plugin "https://github.com/onsip/onsip-cordova.git" via git clone
Installing "com.onsip.cordova" for ios
Failed to install 'com.onsip.cordova':Error: "/Users/DnV/Projects/SIP/test3/platforms/ios/cordova/build" not located within project!
    at Object.module.exports.common.copyFile (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/common.js:55:19)
    at Object.module.exports.common.asset.install (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/common.js:116:20)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/prepare.js:117:26
    at Array.forEach (native)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/prepare.js:116:16
    at Array.forEach (native)
    at Object.handlePrepare (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/prepare.js:81:24)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:599:21
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)

**Comment by InspectorConstructor** [comment]
So, a cordova-lib commit on 10/29/14 is causing this. Since the commit, cordova verifies that all <asset> inside your plugin.xml have targets within the www directory of the platform.
For example, this directory would be `/Users/nick/CordovaRoot/platforms/ios/www` . Since there is an asset tag in your plugin.xml that targets a directory outside this dir, cordova is throwing up.
(the asset tag in on line 23: `<asset src="build" target="../cordova/build" />`)

One person has already weakly complained about this on the cordova-lib git: https://github.com/apache/cordova-lib/commit/281aee737dbe5143c9cb5957359ed5df6298a154#comments
I don't know what they plan to do. I looked into the apache jira for two minutes and didn't see  anyone else complaining about the change.

You could always require an older version of cordova in the meantime. The commit we're concerned with is "CB-7890" and according to their release notes, this commit went into version 4.1.2. see https://github.com/apache/cordova-lib/blob/master/cordova-lib/RELEASENOTES.md#412-nov-13-2014
 IF this is accurate, the latest cordova that should be compatible is version 4.1.1. 

Please let me know what you plan to do - I did a lot of digging to figure this out @__@

**Comment by InspectorConstructor** [comment]
fyi the bug goes back to at least 4.1.0. I wasn't able to test 4.0.x but version 3.6.3-0.2.13 installs correctly, at least.

**Comment by egreenmachine** [comment]
@InspectorConstructor thanks for doing the research on this. I am trying to find some time to get around to looking at this and fixing it.

**Comment by Iliyass** [comment]
guys i still have this error in cordova 4.2.0, please how i can fix this ??? i'm using Ionic

**Comment by egreenmachine** [comment]
Hi @Iliyass,

I have not had time to upgrade this project to the new version of Cordova. Could you please try downgrading to version 3.X and see if that resolves your issue?

**Comment by AaronEckhart** [comment]
Hey all, I have tried this with 4.2.0 and version 3.6.3-0.2.13 and still had no success. Should I try an older version??  I am working with a few people to get this working, and we would like to help in any way to escalate this ticket. Please let me know... Thanks!

**Comment by egreenmachine** [comment]
This issue was Cordova closing a security hole I was using to get the build file in place. I have updated the plugin.xml to no longer do this, and included instructions to copy the build file to the correct location. Commit 9ea6808 resolves this. Tested with Cordova 4.2.0.

**Comment by AaronEckhart** [comment]
@egreenmachine Thanks man! Appreciate your effort. Let me know if you need anything on this.
